# Generated by Django 5.0.4 on 2024-04-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=100)),
                ('permalink', models.IntegerField()),
                ('content', models.TextField(blank=True)),
                ('media_urls', models.JSONField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
